#
#       Copyright (c) 2001 NEC Corporation
#
#       NEC SOURCE CODE PROPRIETARY
#
#       Use, duplication and disclosure subject to a source code
#       license agreement with NEC Corporation.
#

# "@(#) $Id: Makefile,v 1.2300 2003/11/24 00:54:35 nsadmin Exp $"

include $(SRC)/makefile.rule

FILES=default.css	\
	controll.js	\
	tree.js		\
	menu.js

all:	$(FILES)
	-mkdir $(WEBAPPS)/lib
	cp $(FILES) $(WEBAPPS)/lib
