#
#       Copyright (c) 2001 NEC Corporation
#
#       NEC SOURCE CODE PROPRIETARY
#
#       Use, duplication and disclosure subject to a source code
#       license agreement with NEC Corporation.
#

# "@(#) $Id: Makefile,v 1.2300 2003/11/24 00:54:34 nsadmin Exp $"

include	$(SRC)/makefile.rule

SRC=SoapManager.java	\
	SoapLite.java	\
	SoapResponse.java

CLASS=$(SRC:.java=.class)

all: $(CLASS)

clean: 
	rm -f $(CLASS)
